### ISSUE TITLE
Failed to connect to Elevation API in EarthMesh node

### ISSUE THREAD

**Issue by syntheticperson** [xjorma/EarthMeshHoudini#18]
I followed the instructions, including setting up my Google Maps Elevation API, and installing the python libraries.
I tested the API and confirmed that it's working via web requests.
However, when I try to use the EarthMesh HDA, I get the following errors:
Houdini Terminal where I launch Houdini from the command line:

```
Failed to connect to Elevation API, defaulting to zero.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
failed to connect to geographiclib.sourceforge.io, defaulting to zero.
```

Here are the errors I get in the EarthMesh node:

```
Invalid source /obj/geo1/EarthMesh1/3D_Tiles.
(Error: Python error: Traceback (most recent call last):
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1294, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1340, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1289, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1048, in _send_output
self.send(msg)
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 986, in send
self.connect()
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1466, in connect
self.sock = self._context.wrap_socket(self.sock,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
return self.sslsocket_class._create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1108, in _create
self.do_handshake()
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1383, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 141, in 
File "", line 19, in bytes_from_url
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
response = self._open(req, data)
^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
result = func(*args)
^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
return self.do_open(http.client.HTTPSConnection, req,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Applications/Houdini/Houdini20.5.278/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
raise URLError(err)
urllib.error.URLError: 
).
```

What am I missing? Here is my Houdini setup.
`Houdini 20.5.278 - Py3.11`
`OS: MacOS Sonoma 14.1`
`Hardware: MacBook Pro M1 (2021)`

**Comment by xjorma** [comment]
It's an issue with Mac and Linux. I have to investigate this. I am very busy with other things right now, but I will check it as soon as I can.

**Comment by syntheticperson** [comment]
In that case, I'll try your EarthMesh HDA in Houdini on Windows.
Thanks

**Comment by syntheticperson** [comment]
In the meantime, it might be helpful to others that you add to the documentation that EarthMesh HDA has only been tested on Windows.

**Comment by jlapreviz** [comment]
I managed to get EarthMesh working on Windows.
Many thanks
Please close this issue, as I'm not seeing that option available for me.

**Comment by syntheticperson** [comment]
I managed to get EarthMesh to work on Windows!
Many thanks.
