### ISSUE TITLE
error 403 & request.py 

### ISSUE THREAD

**Issue by maximefauure** [xjorma/EarthMeshHoudini#2]
I do get an error message on the earthmesh node (i gave my google api key & cache folder + python libraries installed & lab) 

I m on windows, with houdini 19.5.493 py3.9 

I would like to now which version of houdini should we pick to get the same setup as you

"

Error 
Invalid source /obj/geo1/EarthMesh1/3D_Tiles
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 126, in <module>
File "<stdin>", line 11, in bytes_from_url
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 523, in open
response = meth(req, response)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 632, in http_response
response = self.parent.error(
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 561, in error
return self._call_chain(*args)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 494, in _call_chain
result = func(*args)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.493\python39\lib\urllib\request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
. 

"

**Comment by xjorma** [comment]
Hello Maxime,
I use 19.5.640  but it shouldn't make a difference.
If you got there it means your google key is at least half good (Elevation
is working). Wild guest are you sure you enabled the tile API?
There is almost no error handling in this source. I should improve that.

**Comment by xjorma** [comment]
I have exactly the same error if I disable the Tile API.

[image: image.png]

**Comment by faddysaeed** [comment]
same problem here too.
 itried the exaple file after following the installation instruction, but got the same error.

**Comment by Tyler-English** [comment]
got the same error. 
appreciate any assistance

Invalid source /obj/geo1/EarthMesh1/3D_Tiles
Error: Python error: Traceback (most recent call last):
File "", line 126, in
File "", line 11, in bytes_from_url


line 126 from the node it directs you to. 
125 # read Root
126 b = bytes_from_url(tile_url + root_cmd + "?key=" + api_key, False)
127 res = json_from_byte(b)\

i am assuming it is not creating / passing the json file needed to generate the tile. Trying to trouble shoot. I believe all the map tile api / elevation api are enabled. Not sure why the error message. please update with a fix if anyone figures it out. 
Thanks.

**Comment by Tyler-English** [comment]
new error message.  I tried to double-check pip, it was fine. b/c i was able to reload the hython files and reset houdini. 
some files cached but not others. 
Houdini console read out
Download D:/houdini/cache//UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NDQscGF0aD0zMTYyNixjYWNoZV92ZXJzaW9uPTYsaW1hZ2VyeV9lcG9jaD05NjA.glb
Collected 2371 meshes, 839 meshes downloaded
north = {0.445473,0.812532,0.375959}
east = {-0.645020,0.000000,0.764166}
up = {-0.620909,0.582917,-0.524099}
Download D:/houdini/cache//root.json
Collected 2371 meshes, 0 meshes downloaded
north = {0.445473,0.812532,0.375959}
east = {-0.645020,0.000000,0.764166}
up = {-0.620909,0.582917,-0.524099}
Download D:/houdini/cache//root.json
Collected 2371 meshes, 0 meshes downloaded


Then a new error showed up. still troubleshooting.  

Invalid source /obj/geo1/EarthMesh1/Glb
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 2, in <module>
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "src/DracoPy.pyx", line 1, in init DracoPy
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\__init__.py", line 139, in <module>
from . import core
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\core\__init__.py", line 73, in <module>
from . import numeric
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\core\numeric.py", line 23, in <module>
from . import shape_base
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\core\shape_base.py", line 11, in <module>
from ._asarray import array, asanyarray
File "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\core\_asarray.py", line 11, in <module>
from .multiarray import array, asanyarray
ImportError: cannot import name 'asanyarray' from 'numpy.core.multiarray' (C:\PROGRA~2\Steam\STEAMA~1\common\HOUDIN~1\python39\lib\site-packages\numpy\core\multiarray.py)

I'm looking at multiarray.py to better understand the error but not sure what 'asanyaary' or why it isn't importing. 
.

**Comment by xjorma** [comment]
for those who still have http issues. 
Could you test this?:
You can test if your key supports the Map Tiles API by trying this link on your favorite browser https://tile.googleapis.com/v1/3dtiles/root.json?key=YOUR_API_KEY, replace YOUR_API_KEY by your key, if you see an error message it's not good, and you need to check again your account.
You can test if your key supports the Elevation API by trying this link on your favorite browser https://maps.googleapis.com/maps/api/elevation/json?locations=39.7391536%2C-104.9847034&key=YOUR_API_KEY, replace YOUR_API_KEY by your key, if you see an error message it's not good, and you need to check again your account.

**Comment by xjorma** [comment]
For the python error it's strange I don't understand why it cannot import the package. Which version of Houdini are you using? On which OS?

**Comment by faddysaeed** [comment]
> For the python error it's strange I don't understand why it cannot import the package. Which version of Houdini are you using? On which OS?

19.5. 435 py3.9 windows 10

**Comment by xjorma** [comment]
Almost the same than me, expect I am using 19.5.640, should not make a huge difference.

**Comment by Tyler-English** [comment]
Houdini 19.5.684 py3.9 windows 10

map tiles check 
{"asset":{"version":"1.0"},"geometricError":1e+100,"root":{"boundingVolume":{"box":[0,0,0,7972671.25,0,0,0,7972671.25,0,0,0,7945940.3928064629]},"geometricError":1e+100,"refine":"REPLACE","transform":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"children":[{"boundingVolume":{"box":[0,0,0,7972671.25,0,0,0,7972671.25,0,0,0,7945940.3928064629]},"geometricError":1e+100,"refine":"REPLACE","children":[{"boundingVolume":{"box":[0,0,0,7972671.25,0,0,0,7972671.25,0,0,0,7945940.3928064629]},"geometricError":1e+100,"content":{"uri":"/v1/3dtiles/datasets/CgA/files/UlRPVEYuYnVsa21ldGFkYXRhLnBsYW5ldG9pZD1lYXJ0aCxidWxrX21ldGFkYXRhX2Vwb2NoPTk1NSxwYXRoPSxjYWNoZV92ZXJzaW9uPTY.json?session=COGbnuitz431chCX-rOnBg"}}],"extras":{"comment":"path = ''"}}]},"extensionsUsed":["3DTILES_content_gltf"],"extensionsRequired":["3DTILES_content_gltf"]}


elevation check 
{
   "results" : 
   [
      {
         "elevation" : 1608.637939453125,
         "location" : 
         {
            "lat" : 39.7391536,
            "lng" : -104.9847034
         },
         "resolution" : 4.771975994110107
      }
   ],
   "status" : "OK"
}

**Comment by xjorma** [comment]
@Tyler-English your key is good, but I already knew it, if you have this message "Collected 2371 meshes, 0 meshes downloaded" it's means your Google API work is done. Unfortunately I don't understand your new issue, it's very strange. :(

**Comment by Tyler-English** [comment]
okay thanks for the update ill let you know if anything changes or i figure it out. Cool tool though, cheers.

**Comment by cds1503** [comment]
hello. Is the environment you are testing offline + proxy server?
We are only thinking of Google-API, but it turns out that we can't find the following path.
https://geographiclib.sourceforge.io/
So I added that path and the above problem was solved.

**Comment by faddysaeed** [comment]
after the download:
consol message:
E:/H_Hip/cache/cache/UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NDQscGF0aD0zMTYyNixjYWNoZV92ZXJzaW9uPTYsaW1hZ2VyeV9lcG9jaD05NjA.glb
Collected 2330 meshes, 2330 meshes downloaded

but on the had node error:

Invalid source [/obj/GoogleMap/EarthMesh/Glb](node:/obj/GoogleMap/EarthMesh/Glb)
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\Users\FADDY\AppData\Local\Programs\Python\Python37\Lib\site-packages\pygltflib\__init__.py", line 45, in <module>
from dataclasses_json import dataclass_json as dataclass_json
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\Users\FADDY\AppData\Local\Programs\Python\Python37\Lib\site-packages\dataclasses_json\__init__.py", line 2, in <module>
from dataclasses_json.api import (DataClassJsonMixin,
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\Users\FADDY\AppData\Local\Programs\Python\Python37\Lib\site-packages\dataclasses_json\api.py", line 6, in <module>
from dataclasses_json.cfg import config, LetterCase # noqa: F401
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\Users\FADDY\AppData\Local\Programs\Python\Python37\Lib\site-packages\dataclasses_json\cfg.py", line 5, in <module>
from marshmallow.fields import Field as MarshmallowField # type: ignore
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\Users\FADDY\AppData\Local\Programs\Python\Python37\Lib\site-packages\marshmallow\__init__.py", line 3, in <module>
from packaging.version import Version
File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'packaging'

windows 10, houdini 19.5 435 py3.9

thank you

**Comment by xjorma** [comment]
@faddysaeed did you import the python package?

**Comment by faddysaeed** [comment]
yes I imported both successfully

**Comment by arthur-mensch** [comment]
I'm encountering the same error most are here, one thing I did catch is[ the Map Tiles API is set to private](https://i.imgur.com/3CFTb1V.png), could that be the issue that it got set to private, and now keys won't work unless you pay for a higher tier?

**Comment by xjorma** [comment]
@zmandt, my understanding is the Tile API is free but the usage limit is slow (I also use use Elevation API which is need to be paid, but I use it a lot less and you should be far bellow the free tier, but don't thrust me monitor your usage, set notification, I personally set a notification at $1). personally while developing the HDA I never busted the limit. 
But while developing this https://www.linkedin.com/feed/update/urn:li:activity:7102692746892562432/ I busted the limit very quickly. Note that the limit is per project, so I created multiple projects. Also the limit is per day, you just have to wait 24h.

**Comment by xjorma** [comment]
@faddysaeed  Sadly I have no idea why you can't import the python package. I can't help you :(

**Comment by MikhalenkaA** [comment]
hello. have this Error Houdini 19.5.716  Py 3.9. Api keys checkd and work in borwser via links in readme:



Error | Invalid source /obj/GoogleMap/EarthMesh/FindAltitudeError: Python error: Traceback (most recent call last):File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1346, in do_openh.request(req.get_method(), req.selector, req.data, headers,File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1285, in requestself._send_request(method, url, body, headers, encode_chunked)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1331, in _send_requestself.endheaders(body, encode_chunked=encode_chunked)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1280, in endheadersself._send_output(message_body, encode_chunked=encode_chunked)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1040, in _send_outputself.send(msg)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 980, in sendself.connect()File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1454, in connectself.sock = self._context.wrap_socket(self.sock,File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 500, in wrap_socketreturn self.sslsocket_class._create(File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 1040, in _createself.do_handshake()File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 1309, in do_handshakeself._sslobj.do_handshake()ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)During handling of the above exception, another exception occurred:Traceback (most recent call last):File "<stdin>", line 43, in <module>File "<stdin>", line 29, in get_sealevelFile "<stdin>", line 5, in bytes_from_urlFile "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 214, in urlopenreturn opener.open(url, data, timeout)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 517, in openresponse = self._open(req, data)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 534, in _openresult = self._call_chain(self.handle_open, protocol, protocol +File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 494, in _call_chainresult = func(*args)File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1389, in https_openreturn self.do_open(http.client.HTTPSConnection, req,File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1349, in do_openraise URLError(err)urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)>.
-- | --


</body></html>Error 
Invalid source [/obj/GoogleMap/EarthMesh/FindAltitude](node:/obj/GoogleMap/EarthMesh/FindAltitude)
Error: Python error: Traceback (most recent call last):
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1040, in _send_output
self.send(msg)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 980, in send
self.connect()
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\http\client.py", line 1454, in connect
self.sock = self._context.wrap_socket(self.sock,
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 1040, in _create
self.do_handshake()
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 43, in <module>
File "<stdin>", line 29, in get_sealevel
File "<stdin>", line 5, in bytes_from_url
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 517, in open
response = self._open(req, data)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 494, in _call_chain
result = func(*args)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.716\python39\lib\urllib\request.py", line 1349, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)>
.

**Comment by xjorma** [comment]
@MikhalenkaA
mhhh it seems one of the web service I use is down.
https://www.sourceforge.io/cgi-bin/GeoidEval
I will check if I can find an alternative solution.

**Comment by xjorma** [comment]
https://www.sourceforge.io/cgi-bin/GeoidEval is back online could you retry.
I could avoid the use of this "online service" but I will need to ask people to install an additional python library. I will probably just fail more graceful, i am "just" calling those apis to make sure the altitude zero is at floor level. It's not the end of the world if i can't get those value.
