### ISSUE TITLE
Getting a Python Error from 3D_Tiles inside Earth Mesh HDA

### ISSUE THREAD

**Issue by bennihaarna** [xjorma/EarthMeshHoudini#23]
Getting an Error from 3D_Tiles inside Earth Mesh HDA

First time trying to get this running in H20.0.688. Have installed all extra plugins and py extras, correctly I think...

Error 
Python error: Traceback (most recent call last):
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
self.send(msg)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
self.connect()
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
self.sock = self._context.wrap_socket(self.sock,
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 141, in <module>
File "<stdin>", line 19, in bytes_from_url
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
response = self._open(req, data)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/Applications/Houdini/Houdini20.0.688/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by xjorma** [comment]
It sound like an issue that people have on Linux and MacOs. What OS are you using?

**Comment by bennihaarna** [comment]
I'm on Mac OS

**Comment by bennihaarna** [comment]
is Windows the more tested OS for this?

**Comment by xjorma** [comment]
I developed it on windows.
I have access to a mac, but I never used Houdini on it. I will try to find time for this.

**Comment by bennihaarna** [comment]
I will see if I can get it running on a windows boot on my Mac

**Comment by bennihaarna** [comment]
Yes, it seems to work ok on the windows boot on a Mac.

**Comment by bennihaarna** [comment]
Spoke a little soon. Now has an error on python Glb node inside Earth Mesh:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Error | Python error: Traceback (most recent call last):File "<stdin>", line 1, in <module>File "C:\Program Files\Side Effects Software\Houdini 20.0.918\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _importreturn original_import(name, *args, **kwargs)ModuleNotFoundError: No module named 'pygltflib'
-- | --


</body></html>

**Comment by bennihaarna** [comment]
Had to reinstall pygltflib and DracoPy as needed to install a version of Hou with py3.9.
working now in windows bootstrapping on a mac

**Comment by bennihaarna** [comment]
So, I got everything working on Windows. Tried a fresh install on a different mac with the same hou 20.0.922 py3.9 install. Ran all the bits and same error.

**Comment by xjorma** [comment]
Fixed with:
https://github.com/xjorma/EarthMeshHoudini/commit/0ad9ada936ea274191ba6911c3aa6b09d6c4c6b1
