### ISSUE TITLE
Compatibility and Error Resolution Inquiry for EarthMesh with Houdini Apprentice 19.5.795

### ISSUE THREAD

**Issue by natez311** [xjorma/EarthMeshHoudini#9]
I am experiencing issues with the EarthMesh HDA in Houdini Apprentice 19.5.795 on macOS 13.6 and am seeking assistance to resolve these.

**Environment Details:**
Houdini Version: Houdini Apprentice 19.5.795 (Non-Commercial)
Operating System: macOS 13.6
EarthMesh Version: Downloaded on November 15th, 2023 (specific version number not mentioned, please insert if available)
Issue Description:
Upon adding the EarthMesh node to my scene in Houdini (and entering the API code), the node text appears in red, indicating an error. I have followed the installation and setup instructions accurately, but the issue persists.

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Error | Python error: Traceback (most recent call last):File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_openh.request(req.get_method(), req.selector, req.data, headers,File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in requestself._send_request(method, url, body, headers, encode_chunked)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_requestself.endheaders(body, encode_chunked=encode_chunked)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheadersself._send_output(message_body, encode_chunked=encode_chunked)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_outputself.send(msg)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in sendself.connect()File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connectself.sock = self._context.wrap_socket(self.sock,File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socketreturn self.sslsocket_class._create(File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _createself.do_handshake()File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshakeself._sslobj.do_handshake()ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)During handling of the above exception, another exception occurred:Traceback (most recent call last):File "<stdin>", line 133, in <module>File "<stdin>", line 11, in bytes_from_urlFile "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopenreturn opener.open(url, data, timeout)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in openresponse = self._open(req, data)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _openresult = self._call_chain(self.handle_open, protocol, protocol +File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chainresult = func(*args)File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_openreturn self.do_open(http.client.HTTPSConnection, req,File "/Applications/Houdini/Houdini19.5.795/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_openraise URLError(err)urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
-- | --

</body></html>`

**Steps Taken:**
Installed the EarthMesh HDA as per the provided guidelines.
Configured a Google Cloud Account with the necessary APIs (Map Tiles API, Maps Elevation API).
Installed additional Python packages (pygltflib and DracoPy) as directed in the documentation.
Meticulously set up all parameters within the EarthMesh node as recommended.
Despite these efforts, the node continues to show an error.

**Specific Inquiries:**
Compatibility: Is there known compatibility of EarthMesh with Houdini Apprentice version 19.5.795 and macOS 13.6? If compatibility issues are known, could you suggest the optimal version of Houdini for use with EarthMesh?
Troubleshooting: Are there common issues or specific troubleshooting steps for EarthMesh in this environment that I might have missed?
Error Logs: What specific logs or error messages should I look for within Houdini to better understand this issue?

**Comment by evanmathis** [comment]
Having the same certificate issue.
Houdini Indie 20.0.590
Pop_OS 22.4

**Comment by hipsterette** [comment]
Hi, I am having the same issue here ..

Houdini 19.5.773 
Kindly requesting some help on how to overcome this.

**Comment by sirogi** [comment]
Had the same issue as well. Houdini Apprentice, MacOS. 
(bear with me don't know what am doing here.. ) 
From what I gathered poking around,  Houdini ships with its own python, seemed like it's not liking opening the URL, for lack of an SSL certificate. Poking 'round the web, and looking at the error message, 

URLError(err)urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

if you make the HDA editable "Allow editing of contents" and navigate to "3D tile" python container. 
then paste 

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

right after the series of import statements.. seemed to do the trick. probably super unsafe since it disables certificate checking.  Not proficient enough to fix it "properly" unfortunately. use at your own risk.

**Comment by xjorma** [comment]
Fixed with https://github.com/xjorma/EarthMeshHoudini/commit/0ad9ada936ea274191ba6911c3aa6b09d6c4c6b1
